"""update_speaker_and_transcript

Revision ID: 3ee9f2ebf965
Revises: 0006
Create Date: 2026-05-07 22:00:27.207251

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op



revision: str = '3ee9f2ebf965'
down_revision: str | None = '0006'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('speakers', sa.Column('color_label', sa.String(), server_default='blue', nullable=False))
    op.execute("""
        UPDATE transcript_segments ts
        SET speaker_id = s.id
        FROM speakers s
        WHERE ts.meeting_id = s.meeting_id AND ts.speaker_label = s.speaker_label
    """)
    op.execute("DELETE FROM transcript_segments WHERE speaker_id IS NULL")

    op.alter_column('transcript_segments', 'speaker_id',
               existing_type=sa.UUID(),
               nullable=False)

    op.drop_column('transcript_segments', 'speaker_label')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcript_segments', sa.Column('speaker_label', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_transcript_segments_meeting_version_start', 'transcript_segments', ['meeting_id', 'version_no', 'start_ms'], unique=False)
    op.create_index('ix_transcript_segments_fts_text', 'transcript_segments', [sa.literal_column("to_tsvector('simple'::regconfig, text)")], unique=False, postgresql_using='gin')
    op.alter_column('transcript_segments', 'speaker_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('speakers', 'color_label')
    op.create_unique_constraint('roles_code_key', 'roles', ['code'])
    op.create_index('ix_meeting_summaries_meeting_version', 'meeting_summaries', ['meeting_id', 'version_no'], unique=False)
    op.create_index('ix_meeting_summaries_fts_text', 'meeting_summaries', [sa.literal_column("to_tsvector('simple'::regconfig, summary_text)")], unique=False, postgresql_using='gin')
    op.create_index('ix_action_items_meeting_due_date', 'action_items', ['meeting_id', 'due_date'], unique=False)
    # ### end Alembic commands ###
