// Centralized icon barrel to improve tree-shaking and reduce bundle size.
// Export the specific icons used across the app and re-export the LucideIcon type.
export type { LucideIcon } from "lucide-react";

export {
    Calendar,
    CalendarX,
    FolderKanban,
    Settings,
    Users,
    ChevronDown,
    ChevronUp,
    Search,
    X,
    Check,
    Menu,
    Monitor,
    Moon,
    Sun,
    Lock,
    BadgeCheck,
    Bell,
    CreditCard,
    LogOut,
    CircleUser,
    EllipsisVertical,
    MessageSquareDot,
    ChevronRight,
    MailIcon,
    PlusCircleIcon,
    Ellipsis,
    Folder,
    Forward,
    Trash2,
    Command,
    Globe,
    Settings2,
    ChevronLeft,
    ChevronsLeft,
    ChevronsRight,
    ArrowDown,
    ArrowUp,
    ChevronsUpDown,
    EyeOff,
    Loader2Icon,
    ChevronDownIcon,
    ChevronUpIcon,
    // Icon-suffixed variants used by UI primitives
    XIcon,
    CheckIcon,
    ChevronLeftIcon,
    ChevronRightIcon,
    MoreHorizontalIcon,
    MinusIcon,
    SearchIcon,
    CircleCheckIcon,
    InfoIcon,
    TriangleAlertIcon,
    OctagonXIcon,
    PanelLeftIcon,
    // Additional icons used across project pages
    ImagePlus,
    ClipboardPlus,
    Save,
    Plus,
    Clock,
    PlayCircle,
    User,
    ShieldAlert,
    Captions,
    CheckSquare,
    FileText,
    LayoutDashboard,
    Mic,
    AudioLines,
    FileAudio,
    Loader2,
    RefreshCw,
    Upload,
    WandSparkles,
    Edit2,
    ArrowLeft,
    Download,
} from "lucide-react";
